version: '3.8'
services:
  backend:
    container_name: ticketing-backend
    build: ./
    volumes:
      - ./:/var/www/html/ticketing-backend
      - /var/www/html/ticketing-backend/vendor
    ports:
      - 8000:8000
  mysql_db:
    image: mariadb:10.3.23
    # Set max_allowed_packet to 256M (or any other value)
    command: --max_allowed_packet=32505856
    restart: always
    environment:
      - MYSQL_USER=vince1432
      - MYSQL_PASSWORD=1432
      - MYSQL_ROOT_PASSWORD=1432
      - MYSQL_DATABASE=ticket
    ports:
      - 3306:3306
    volumes:
      - .\data\:/var/lib/mysql
#   phpmyadmin:
#     image: phpmyadmin:latest
#     restart: always
#     ports:
#       - 9001:80
#     environment:
#       - PMA_ARBITRARY=1
#       # - MYSQL_USER=vince1432
#       # - MYSQL_PASSWORD=1432
#       # - MYSQL_ROOT_PASSWORD=1432
